CREATE TABLE EMPLOYEE (Emplyee_No int IDENTITY(100,1) PRIMARY KEY,Employee_Name VARCHAR(50) NOT NULL,Gender CHAR(1),Age TINYINT,Salary INT) 

INSERT EMPLOYEE VALUEs ('Raj','M',28,20000)
INSERT EMPLOYEE VALUEs ('Ramu','M',28,30000)
INSERT EMPLOYEE VALUEs ('abi','f',28,27000)
INSERT EMPLOYEE VALUEs ('manibala','M',28,40000)
INSERT EMPLOYEE VALUEs ('mathan','M',28,50000)
INSERT EMPLOYEE VALUEs ('Bindu','f',28,31000)
INSERT EMPLOYEE VALUEs ('Raja','M',28,43000)
INSERT EMPLOYEE VALUES ('Sakthi','f',null,39000)

SELECT MAX(SALARY) FROM EMPLOYEE
SELECT MIN(SALARY) FROM EMPLOYEE
SELECT AVG(SALARY) FROM EMPLOYEE
SELECT COUNT(SALARY),COUNT(age) FROM EMPLOYEE
SELECT COUNT_BIG(Gender) FROM EMPLOYEE
SELECT STDEV(SALARY) FROM EMPLOYEE
SELECT STDEVP(SALARY) FROM EMPLOYEE


SELECT AGE,MAX(SALARY) FROM EMPLOYEE
GROUP BY AGE WITH ROLLUP

SELECT AGE,MAX(SALARY) ,GROUPING (AGE) FROM EMPLOYEE
GROUP BY AGE WITH ROLLUP

SELECT AGE,GENDER,MAX(SALARY),GROUPING_ID(AGE,GENDER) FROM EMPLOYEE
GROUP BY AGE,GENDER WITH ROLLUP

SELECT AGE,GENDER,MAX(SALARY),GROUPING_ID(AGE,GENDER) FROM EMPLOYEE
GROUP BY AGE,GENDER WITH CUBE

SELECT*FROM
(SELECT AGE,GENDER,MAX(SALARY) MIN_SAL,GROUPING_ID(AGE,GENDER) STATUS FROM EMPLOYEE
GROUP BY AGE,GENDER WITH CUBE)Res
WHERE STATUS=3

SELECT * FROM EMPLOYEE

truncate table EMPLOYEE 