INSERT INTO DEPT(DEPTNO,DEPTNAME,DEPTLOCATION) 
SELECT DEPTNO,DEPTNAME,DEPTLOCATION 
FROM DEPARTMENT WHERE DEPTNO=104


SELECT * INTO DEPT FROM DEPARTMENT
DROP TABLE  DEPT
TRUNCATE TABLE DEPT
SELECT *FROM DEPT