CREATE TABLE EMPLOYEE1 (EMPID INT,ENAME CHAR(30),JOB VARCHAR(30),DEPTTY INT)

INSERT INTO EMPLOYEE1 VALUES (69,'KURU','SIMTCLERK',10 )
INSERT INTO EMPLOYEE1 VALUES (7354,'SIMTH','SALESMAN',30)
INSERT INTO EMPLOYEE1 VALUES (7323,'BALA','SALESMAN',21)
INSERT INTO EMPLOYEE1 VALUES (7372,'MURUGA','MANAGER',45)

INSERT INTO EMPLOYEE1 VALUES (7365 ,'GANPATHI','SALESMAN',10)
INSERT INTO EMPLOYEE1 VALUES (7342,'MILK','ANALYIST',30)
INSERT INTO EMPLOYEE1 VALUES (7331,'SIM','ANALYIST',13)
INSERT INTO EMPLOYEE1 VALUES (7311,'SIMTH','SIMCLEARK',10)
INSERT INTO EMPLOYEE1 VALUES (7395,'RAHU','CLERK',12)

--BELOW METHOD ONLY USED BY SINGLE COLUMN 

SELECT JOB,COUNT(*)FROM EMPLOYEE1 GROUP BY JOB
SELECT JOB,SUM(DEPTTY)FROM EMPLOYEE1 GROUP BY JOB

SELECT JOB,MAX(DEPTTY) MAXIMU,MIN(DEPTTY) MINSA,AVG(DEPTTY) AVGSAL
FROM EMPLOYEE1 GROUP BY JOB

--USE TWO COLUMN IN GROUPING BELOW 

SELECT JOB,COUNT(*)NUMBEROFEP,DEPTTY FROM EMPLOYEE1 GROUP BY JOB,DEPTTY

--USE HAVING KEY WORD

SELECT JOB,COUNT(*) FROM EMPLOYEE1 GROUP BY JOB HAVING COUNT(*)>1
SELECT JOB,SUM(DEPTTY) GRE FROM EMPLOYEE1 GROUP BY JOB HAVING SUM(DEPTTY)>20

SELECT*FROM EMPLOYEE1