--USE TWO TABLE SO THIS COMPLEX VIEW SO DML OPERATION WE CAN'T DO

USE mathan

CREATE VIEW CV1 AS
SELECT *FROM EMPD_CHENNAI
UNION
SELECT *FROM EMPD_HYP

INSERT INTO CV1 VALUES(106,'ABC',20000)--BECOME ERROR it contains a derived or constant field.
UPDATE CV1 SET EMPSALARY=30000 WHERE EMPID=101--BECOME ERROR it contains a derived or constant field.
DELETE FROM CV1 WHERE EMPID=101--BECOME ERROR the definition contains a UNION operator.


SELECT*FROM EMPD_CHENNAI
SELECT*FROM EMPD_HYP
SELECT*FROM CV1