CREATE TABLE DEMO1 (DEMOID INT UNIQUE,CITY VARCHAR(30))
CREATE TABLE DEMO2 (DEMOID INT NOT NULL,CITY VARCHAR(30)NOT NULL)
CREATE TABLE DEMO3 (DEMOID INT,SALARY MONEY CHECK(SALARY>5000))

--ONLY DEMOID VARIALBLE WILL ASSIGN UNIQUE KEY
INSERT DEMO1 VALUES (101,'RAJ')
INSERT DEMO1 VALUES (102,'RAJ')
--NULL ALSO ACCEPT
INSERT DEMO1 VALUES (NULL,NULL)

-- NOT NULL KEY WORD DEMO THE NULL VALUES ARE NOT ACCEPT
INSERT DEMO2 VALUES (NULL,NULL)

--DEMO FOR CHECK KEY WORD
INSERT DEMO3 VALUES(12,5500)
INSERT DEMO3 VALUES(12,5500)--NOT ACCEPT BELOW 5000


SELECT*FROM DEMO1