--CREATE TABLE EMPLOYEE(EMPID INT,EMPNAME CHAR(10),SALARY MONEY,AGE TINYINT)
SP_HELP EMPLOYEE

ALTER TABLE  TABLEEMP ALTER COLUMN EMPOLYEENAME CHAR(10)

ALTER TABLE TABLEEMP ADD EMPADDRESS VARCHAR(30)

SP_RENAME'TABLEEMP.EMPNAME','EMPNAMES';

SP_RENAME'TABLEEMP','EMPDETAILS';

ALTER TABLE EMPDETAILS DROP COLUMN EMPADDRESS;

--SP_RENAME EMPLOYEE.EMPID,EPID--------TO CHANGE COLUMN NAME
--SP_RENAME EMPLOYEE,NEWEMPLOYEE----------TO CHANGE A TABLE NAME

SELECT*FROM EMPDETAILS;
TRUNCATE TABLE EMPDETAILS;


