CREATE TABLE TEST1(IDNUM INT,NAME VARCHAR(30))
CREATE TABLE TEST2(IDNUM INT,NAME VARCHAR(30))

--EQUI JOIN
SELECT*FROM TEST1,TEST2 WHERE TEST1.IDNUM=TEST2.IDNUM
--NON EQUI JOIN
SELECT*FROM TEST1,TEST2 WHERE TEST2.IDNUM>TEST1.IDNUM





SELECT*FROM TEST1
SELECT*FROM TEST2
