--NON-CORELATED SQ;
1 ST HIGHEST SALARY EMPLOYEE DETAILS:

SELECT*FROM EMP WHERE SALARY=(SELECT MAX(SALARY) FROM EMP)

2 ST HIGHEST SALARY EMPLOYEE DETAILS:

SELECT*FROM EMP WHERE SALARY=(SELECT MAX(SALARY) FROM EMP WHERE SALARY<(SELECT MAX(SALARY) FROM EMP)
WHERE SALARY<(SELECT MAX(SALARY) FROM EMP))

--TO FIND THE nth hightest salary 
SELECT*FROM EMP E1 WHERE 0=(SELECT COUNT(SALARY) FROM EMP E2 WHERE E1.SALARY<E2.SALARY)