CREATE TABLE STUDENT(STID INT,SNAME VARCHAR(40),SFEE DECIMAL(6,2),AGE TINYINT);
--this method you should fill all given datas
INSERT INTO STUDENT VALUES (101,'RAM',3000,18)
--this method only fill assigen datas
INSERT INTO STUDENT (STID,SNAME,AGE) VALUES (102,'VICKY',23)
INSERT INTO STUDENT VALUES (101,'KUMR',3900,18)
INSERT INTO STUDENT (STID,SNAME,SFEE) VALUES (102,'VICKY',4500)
--update the column specific value 
UPDATE STUDENT SET SFEE=5300 WHERE STID=101
UPDATE STUDENT SET SFEE=2900 WHERE STID=102	
--update the only null value
UPDATE
	STUDENT 
SET
	AGE=28
WHERE 
	AGE IS NULL
--all column are update
UPDATE STUDENT SET SFEE=3000
--DELETE FROM STUDENT WHERE AGE IS NULL
--DELETE FROM DEMO03 WHERE EPNAME='BAC'--ONLY COLUMN DELETE
--DELETE FROM  STUDENT--ALL TABLE DELETE
SELECT
	*
FROM 
	STUDENT



