--THIS DQL OR DRL USED TO ONLY SHOW THE SINGLE COLUMN VALUES---

-- * IS REPRESENT THE ALL VALUE IN TABLE
SELECT*FROM [DQL OR DRL DEMO]
--BELOW SYNTAX ALSO SHOW THE ALL VALUES WITHOUT CONDTION
SELECT STID,STNAME,STCLASS,STGRADE FROM [DQL OR DRL DEMO]	


--THIS SYNTAX SHOW THE ROCKY ALL INFORMATION BY USE *
SELECT*FROM [DQL OR DRL DEMO] WHERE STNAME='ROCKY'
--
SELECT STCLASS,STGRADE FROM [DQL OR DRL DEMO] WHERE STID=103
SELECT*FROM [DQL OR DRL DEMO]

