--THIS IDENTITY  USE TO AUTO UPDATE THE VALUE--

CREATE TABLE EMP (EPID INT IDENTITY,EMPNAME CHAR(40),SALARY MONEY)

--DEFAULT SEED IDENTITY FUNCTION INCRMENT AUTOMATICALY +1

INSERT INTO EMP (EMPNAME,SALARY) VALUES ('AA',2300)
INSERT INTO EMP VALUES ('BB',3000),('CC',4000),('DD',5000)
SELECT*FROM EMP

_____________________________________________________

--USER DEFINE IDENTITY SEED INCREMENTAL VALUE

CREATE TABLE EMP1(EMPID INT IDENTITY(100,5),EMPNAME CHAR(40),SALARY MONEY)

INSERT INTO EMP1 VALUES ('AA',2000),('AB',2000),('AC',2000),('AD',2000),('AE',2000)

-- IF THE IDENTITY IS ON WE CAN ASSIGEN THE VALUE 
SET IDENTITY_INSERT EMP1 ON

INSERT INTO EMP1 (EMPID,EMPNAME,SALARY) VALUES (135,'AF',3000)

-- IF THE IDENTITY IS OFF WE CAN'T ASSIGEN THE VALUE 

SET IDENTITY_INSERT EMP1 OFF 

SELECT*FROM EMP1







