CREATE TABLE STUDENT (STID INT,STNAME CHAR(30),STMAILID VARCHAR(50),COURSEID INT)

CREATE TABLE COURSE (COURSEID INT,CNAME VARCHAR(50),CFEEN DECIMAL(6,2))

SELECT*FROM STUDENT INNER JOIN COURSE ON STUDENT.COURSEID = COURSE.COURSEID

SELECT*FROM STUDENT S RIGHT OUTER JOIN  COURSE C ON S.COURSEID=C.COURSEID

SELECT*FROM STUDENT S LEFT OUTER JOIN  COURSE C ON S.COURSEID=C.COURSEID

SELECT*FROM STUDENT S FULL OUTER JOIN  COURSE C ON S.COURSEID=C.COURSEID

SELECT*FROM STUDENT CROSS JOIN COURSE



