CREATE TABLE EMP2 (EID INT,ENAME CHAR(2),SALARY MONEY,DEPNO INT)

--UPDATE EMP2 SET SALARY=12000 WHERE EID=10SELECT*FROM EMP2

--ROW_NUMBER FUNCTION
SELECT ENAME,SALARY,ROW_NUMBER() OVER (ORDER BY SALARY DESC) AS RANKS FROM EMP2
--RANK() FUNCTION
SELECT ENAME,SALARY,RANK() OVER (ORDER BY SALARY DESC) AS RANKS FROM EMP2
--DENSE_RANK() FUNCTION
SELECT ENAME,SALARY,DENSE_RANK() OVER (ORDER BY SALARY DESC) AS RANKS FROM EMP2

SELECT ENAME,DEPNO,SALARY,RANK() OVER(PARTITION BY DEPNO) ORDER BY SALARY DESC)AS RANKS FROM EMP2
