CREATE TABLE EMPLOYEE (EPID INT,EPNAME VARCHAR(30),SALARY MONEY)

INSERT INTO EMPLOYEE VALUES (101,'JONS',25000),(102,'MARK',15000),(103,'LEXLUTHE',20000)

CREATE FUNCTION F_GRSAL(@EPID INT)
RETURNS MONEY
AS
BEGIN
DECLARE @BASIC MONEY,@HRA MONEY,@DA MONEY,@PF MONEY,@GROSS MONEY
SELECT @BASIC=SALARY FROM EMPLOYEE WHERE EPID=@EPID
SET @HRA=@BASIC*0.1
SET @DA=@BASIC*0.2
SET @PF=@BASIC*0.1
SET @GROSS=@BASIC+@HRA+@DA+@PF
RETURN @GROSS
END

SELECT DBO.F_GRSAL(101)

SELECT*FROM EMPLOYEE




