CREATE TABLE EMPD_HYP(EMPID INT,EMPNAME VARCHAR(30),EMPSALARY MONEY)
CREATE TABLE EMPD_CHENNAI(EMPID INT,EMPNAME VARCHAR(30),EMPSALARY MONEY)

--UNION TO SHOW THE ALL DATA IN TWO TABLES BUT WITHOUT DUPLICATE 
SELECT EMPNAME  FROM EMPD_CHENNAI
UNION
SELECT EMPNAME  FROM EMPD_HYP

--TO SHOW THE ALL DATA IN TWO TABLES 
SELECT EMPNAME  FROM EMPD_CHENNAI
UNION ALL
SELECT EMPNAME  FROM EMPD_HYP

--TO SHOW THE COMMON DUPLIVATE DATA 
SELECT EMPNAME  FROM EMPD_CHENNAI
INTERSECT
SELECT EMPNAME  FROM EMPD_HYP

--TO SHOW THE FIRST GIVEN DATA INFORMATION WITH OUT DUPLICATES
SELECT EMPNAME  FROM  EMPD_HYP
EXCEPT
SELECT EMPNAME  FROM EMPD_CHENNAI