CREATE TABLE DEMODML (EPFA VARCHAR(30),EPNAME VARCHAR(30),EPMO VARCHAR(30))

INSERT INTO DEMODML VALUES ('AAA','JONS','AAA'),('BBB','MARK','BBB'),('CCC','abc','CCC')

SELECT*FROM DEMODML

DROP TABLE DEMODML