--USE MYCLASS
CREATE PROCEDURE SP2(@EPID INT,@PF INT OUT,@PT INT OUT)
AS
BEGIN
DECLARE @SAL MONEY
SELECT @SAL=SALARY FROM EMPLOYEE WHERE EPID=@EPID
SET @PF=@SAL*0.1
SET @PT=@SAL*0.2
END
--Below syntax is not support procedure quriy 
--EXECUTE SP1 102

--This Correct Syntax for procedure Print bind

DECLARE @bPF INT,@bPT INT
EXECUTE SP2 101,@BPF OUT,@BPT OUT
PRINT 'PROVIDENT FUND IS :'+CAST(@bPF AS VARCHAR)
PRINT 'PROFESSIONAL TAX :'+CAST(@bPT AS VARCHAR)




