USE mathan
--Single row SubQuriese
--Step 1
--MAX IS A AGGREGATE FUNCTION SO WE CON'T USE IN (WHERE) CONDITION--SO THAT'S YOU WE USE THE (SUB QURIES)
--INNER QURIE

SELECT
	MAX(SALARY) 
FROM 
	EMPLOYEE


--STEP 2
--OUTER QURIE
--SELECT*FROM EMPLOYEE WHERE SALARY=(INNER QUERY)

--Step 3

SELECT
	*
FROM 
	EMPLOYEE
WHERE 
	SALARY=(SELECT
				MAX(SALARY)
			FROM 
				EMPLOYEE)

--Multiple Row SubQuriese

SELECT
	*
FROM 
	EMPLOYEE
WHERE 
	EMPNAME =(SELECT
				EMPNAME 
			FROM 
				EMPLOYEE
			WHERE 
				EMPNAME='MAX' OR 
					EMPNAME='JHON')--ERROR BECAUSE THIS CAN'T RETURN MORE THEN ONE VALUE
--FIRST METHOD
SELECT
	*
FROM 
	EMPLOYEE
WHERE 
	EMPNAME IN (SELECT 
					EMPNAME 
				FROM 
					EMPLOYEE
				WHERE 
					EMPNAME='MAX' OR 
						EMPNAME='JHON')

--SECOND METHOD
SELECT*FROM EMPLOYEE WHERE EMPNAME IN (SELECT EMPNAME FROM EMPLOYEE WHERE EMPNAME IN ('MAX','JHON')


