CREATE TABLE BRANCH(BCODE INT,BNAME VARCHAR(50),BLOCATION VARCHAR(50))

INSERT INTO BRANCH VALUES (1021,'SBI','HYND')

UPDATE  BRANCH SET BLOCATION='CHENNAI'WHERE BCODE=1021
DELETE FROM BRANCH WHERE BCODE=1021

BEGIN TRANSACTION
ROLLBACK

--BY DEFAULT DML OPERATION ARE AUTOCOMMITED OPERATION THIS DONE BY IMPLICITE
--SO WE CAN'T ROLLBACK 

SELECT*FROM BRANCH