--SAVE POINTER DEMO
CREATE TABLE BRANCH(BCODE INT,BNAME VARCHAR(50),BLOCATION VARCHAR(50))
INSERT INTO BRANCH VALUES (1021,'SBI','HYND'),(1022,'axis','karnataka'),(1023,'icic','chennai'),(1024,'sbi','MUMBAI')
,(1025,'IOB','BANGLURE')


BEGIN TRANSACTION
DELETE FROM BRANCH WHERE BCODE=1024
DELETE FROM BRANCH WHERE BCODE=1022
SAVE TRANSACTION S1--DECLEAR THE SAVE POINTER THE VALUE WILL SAVE 
DELETE FROM BRANCH WHERE BCODE=1023




BEGIN TRANSACTION
ROLLBACK TRANSACTION  S1

BEGIN TRANSACTION
ROLLBACK

SELECT*FROM BRANCH 