CREATE TABLE BRANCH(BCODE INT,BNAME VARCHAR(50),BLOCATION VARCHAR(50))


BEGIN TRANSACTION--ONCE USE BGGIN TRANSACTION KEY WORD WE CAN ROLLBACK 
INSERT INTO BRANCH VALUES (1021,'SBI','HYND')
COMMIT--AFTER THAT WE DECLEAR THE COMMIT AND RUN AFTER THAT WE CAN'T ROLLBACK

BEGIN TRANSACTION--ONCE USE BGGIN TRANSACTION KEY WORD WE CAN ROLLBACK
DELETE FROM BRANCH WHERE BCODE=1021
COMMIT--AFTER THAT WE DECLEAR THE COMMIT AND RUN AFTER THAT WE CAN'T ROLLBACK

BEGIN TRANSACTION
ROLLBACK


SELECT*FROM BRANCH