--SINGLE TABLE VIEW
CREATE VIEW V1 AS SELECT*FROM EMPLOYEE

SELECT*FROM V1
SELECT*FROM EMPLOYEE

--IF WE UPDATE THE EMPLOYEE TABLE V1 ALSO UDATE 
--WHICH DML ACTION DO EMPLOYEE TABLE THAT ACTION ALSO AFFECT
UPDATE  EMPLOYEE SET EMPNAME='LUTHERV' WHERE EMPID=105

