--WITH OUT CURSOR VARIABLE:

DECLARE C1 CURSOR SCROLL FOR SELECT*FROM EMP04
OPEN C1
FETCH LAST FROM C1
FETCH PRIOR FROM C1
FETCH ABSOLUTE 7 FROM C1
FETCH RELATIVE -2 FROM C1
FETCH FIRST FROM C1
FETCH NEXT FROM C1
CLOSE C1

--WITH CURSOR 

DECLARE C2 CURSOR SCROLL FOR SELECT EPID,EPNAME FROM EMP04
DECLARE @EPID INT,@EPNAME VARCHAR(30)
OPEN C2
FETCH LAST FROM C2 INTO @EPID,@EPNAME
PRINT'THE EMPLOYEE'+@EPNAME+''+'ID IS:' +CAST(@EPID AS VARCHAR)
FETCH PRIOR C2 INTO @EPID,@EPNAME
PRINT'THE EMPLOYEE'+@EPNAME+''+'ID IS:' +CAST(@EPID AS VARCHAR)
FETCH ABSOLUTE 9 C2 INTO @EPID,@EPNAME
PRINT'THE EMPLOYEE'+@EPNAME+''+'ID IS:' +CAST(@EPID AS VARCHAR)
FETCH RELATIVE 2 C2 INTO @EPID,@EPNAME
PRINT'THE EMPLOYEE'+@EPNAME+''+'ID IS:' +CAST(@EPID AS VARCHAR)
FETCH FIRST C2 INTO @EPID,@EPNAME
PRINT'THE EMPLOYEE'+@EPNAME+''+'ID IS:' +CAST(@EPID AS VARCHAR)
FETCH NEXT C2 INTO @EPID,@EPNAME
PRINT'THE EMPLOYEE'+@EPNAME+''+'ID IS:' +CAST(@EPID AS VARCHAR)
CLOSE C1
DEALLOCATE C2








